### ISSUE TITLE
Does it support Datastax graph

### ISSUE THREAD

**Issue by gongshaojie12** [PommeVerte/gremlin-php#31]

**Comment by PommeVerte** [comment]
it should. This supports Gremlin-server and last time I checked that's what datastax uses :)

**Comment by JarCzeS** [comment]
how can i communicate with datastax graph, sending system.graphs() return list of my graphs but how can i connect to chosen graph ex. TEST_GRAPH. Any use of "g" or "graph" returns No such property: ... . From php i cant call ":remote config alias g TEST_GRAPH.g" (getting Script13.groovy: 1: unexpected token: : @ line 1, column 1.)

**Comment by PommeVerte** [comment]
The graph and traversal (`g`) are set on the gremlin server end. In the `gremlin-server.yaml` file and scripts file respectively. 

You can find examples of those files here:
https://github.com/PommeVerte/gremlin-php/blob/master/build/server/gremlin-server-php.yaml
Notice the following sections.
```yaml
graphs: {
  graph: conf/tinkergraph-empty.properties ,
  graphT: conf/neo4j-empty.properties
}
#...
scripts: [scripts/gremlin-php-script.groovy]},
#...
```

and here : 
https://github.com/PommeVerte/gremlin-php/blob/master/build/server/gremlin-php-script.groovy
```groovy
globals << [g : graph.traversal(), t : graphT.traversal()]
```

When these are set up, in the above examples you can use the global aliases `graph`, `graphT`, `t` and `g` in your queries.
